<a href="https://colab.research.google.com/github/AdersonLongo/DevBlockchain/blob/main/Trab1_redes_neurais_Aderson.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [38]:
import numpy as np
import enum

dic_entrada = {'qtde_entrada': 2, 'qtde_saida': 1 }


In [3]:
dic_entrada['qtde_saida']

1

In [39]:
X = [[0,0],[0,1],[1,0],[1,1]]
ent_log = [[False,False],[False,True],[True,False],[True,True]]
y = [0, 1, 1, 0]

In [52]:
ent_log

[[False, False], [False, True], [True, False], [True, True]]

In [5]:
if ent_log[1][0] == ent_log[1][1]:
    print ("Falso")
else:
    print ("Verd")

Verd


In [54]:
tx_aprend = float(input(print ("Entre com taxa de aprendizagem: ")))
nr_epocas = int(input(print ("Entre com o número de épocas: ")))
qtde_nos_escondidos = int(input(print ("Entre com a qtde de nós da camada escondida: ")))

Entre com taxa de aprendizagem: 
None0.002
Entre com o número de épocas: 
None5
Entre com a qtde de nós da camada escondida: 
None3


In [55]:
tx_aprend
nr_epocas
type(qtde_nos_escondidos)


int

In [41]:
def calc_func_signoide (x):

  return 1 / (1 + np.exp(-x))


In [8]:
 calc_func_signoide(3)



0.9525741268224334

In [42]:
def calc_derivada_parcial (x):
  return x * (1-x)

In [14]:
calc_derivada_parcial(calc_func_signoide(4))

0.017662706213291107

In [11]:
def calc_func_logica (a, b):
    pass

In [39]:
#for ent in (entrada):
print ((entrada[3][1]))

1


In [43]:
# Inicialização dos pesos
def inic_pesos(qtde_nos_escondidos, qtde_entrada, qtde_saida):
    peso_ent_camada_oculta = np.random.rand(qtde_entrada, qtde_nos_escondidos)
    peso_cam_oculta_saida = np.random.rand(qtde_nos_escondidos, qtde_saida)
    return peso_ent_camada_oculta, peso_cam_oculta_saida

In [29]:
(qtde_nos_escondidos)


3

In [44]:
qtd_ent = dic_entrada['qtde_entrada']
qtd_saida = dic_entrada['qtde_saida']
type(qtd_saida)
peso_ent_camada_oculta, peso_cam_oculta_saida = inic_pesos(qtde_nos_escondidos, qtd_ent, qtd_saida)
print (peso_ent_camada_oculta, peso_cam_oculta_saida)

[[0.16259911 0.63543668 0.50068028]
 [0.37010319 0.12064005 0.6944284 ]] [[0.23209445]
 [0.3967039 ]
 [0.96084769]]


In [68]:
def calc_fluxo_volta (X, y, tx_aprend, peso_cam_oculta_saida):

    # Calculando o erro na camada de saída
    erro_saida = y - saida

    # Atualizando os pesos da camada de saída
    delta_output = erro_saida * calc_derivada_parcial(output)
    peso_cam_oculta_saida += np.dot(erro_saida.T, delta_output) * tx_aprend
    bias_output += np.sum(delta_output, axis=0, keepdims=True) * tx_aprend
    print ('bias_output: ', bias_output)

    # Calculando o erro na camada oculta
    hidden_error = np.dot(delta_output, self.weights_hidden_output.T)

    # Atualizando os pesos da camada oculta
    peso_ent_camada_oculta = hidden_error * calc_derivada_parcial(erro_saida)
    weights_input_hidden += np.dot(X.T, delta_hidden) * tx_aprend
    bias_hidden += np.sum(delta_hidden, axis=0, keepdims=True) * tx_aprend


#calc_soma_cam_oculta(entrada, qtde_nos_escondidos, peso_ent_camada_oculta)

In [81]:
erro_saida = y - saida
print ('erro_saida: ', erro_saida)
print ('erro_saida.T: ', erro_saida.T)

erro_saida:  [[-0.68886599  0.31113401  0.31113401 -0.68886599]
 [-0.72877589  0.27122411  0.27122411 -0.72877589]
 [-0.72771041  0.27228959  0.27228959 -0.72771041]
 [-0.76020457  0.23979543  0.23979543 -0.76020457]]
erro_saida.T:  [[-0.68886599 -0.72877589 -0.72771041 -0.76020457]
 [ 0.31113401  0.27122411  0.27228959  0.23979543]
 [ 0.31113401  0.27122411  0.27228959  0.23979543]
 [-0.68886599 -0.72877589 -0.72771041 -0.76020457]]


In [55]:
print ('nr_epocas', nr_epocas)


nr_epocas 5


In [66]:
def calc_fluxo_ida():
    # Camada oculta
    hidden_output = calc_func_signoide(np.dot(X, peso_ent_camada_oculta))

    # Camada de saída
    output = calc_func_signoide(np.dot(hidden_output, peso_cam_oculta_saida))
    print ('outuput: ', output)
    return output

In [70]:
# Para cada epoca, calcula o
print ('nr_epocas', nr_epocas)
for epoca in range(nr_epocas):
    saida = calc_fluxo_ida()
    calc_fluxo_volta(X, y, tx_aprend, peso_cam_oculta_saida)
    if epoca % 1000 == 0:
        print(f'Error: {np.mean(np.abs(y - saida)):.4f}')

print("Output after training:")
print(calc_fluxo_volta(X))

nr_epocas 5
outuput:  [[0.68886599]
 [0.72877589]
 [0.72771041]
 [0.76020457]]


ValueError: operands could not be broadcast together with shapes (3,1) (4,4) (3,1) 