<a href="https://colab.research.google.com/github/AdersonLongo/DevBlockchain/blob/main/Trab1_redes_neurais_Aderson.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

dic_entrada = {'qtde_entrada': 2, 'qtde_saida': 1 }
peso_ent_camada_oculta = []
peso_ent_camada_oculta = []



In [ ]:
type(peso_ent_camada_oculta)



list

In [ ]:
X = [[0,0],[0,1],[1,0],[1,1]]
ent_log = [[False,False],[False,True],[True,False],[True,True]]
y = [0, 1, 1, 0]

In [ ]:
ent_log

[[False, False], [False, True], [True, False], [True, True]]

In [ ]:
if ent_log[1][0] == ent_log[1][1]:
    print ("Falso")
else:
    print ("Verd")

Verd


In [ ]:
tx_aprend = float(input(print ("Entre com taxa de aprendizagem: ")))
nr_epocas = int(input(print ("Entre com o número de épocas: ")))
qtde_nos_escondidos = int(input(print ("Entre com a qtde de nós da camada escondida: ")))

Entre com taxa de aprendizagem: 
None0.1
Entre com o número de épocas: 
None10000
Entre com a qtde de nós da camada escondida: 
None4


In [ ]:
tx_aprend
nr_epocas
type(qtde_nos_escondidos)


int

In [ ]:
def calc_func_signoide (x):

  return 1 / (1 + np.exp(-x))


In [ ]:
 calc_func_signoide(3)



0.9525741268224334

In [ ]:
def calc_derivada_parcial (x):
  return x * (1-x)

In [ ]:
calc_derivada_parcial(calc_func_signoide(4))

0.017662706213291107

In [ ]:
def calc_func_logica (a, b):
    pass

In [ ]:
#for ent in (entrada):
print (X)

[[0, 0], [0, 1], [1, 0], [1, 1]]


In [ ]:
# Inicialização dos pesos
def inic_pesos(qtde_nos_escondidos, qtde_entrada, qtde_saida):
    peso_ent_camada_oculta = np.random.rand(qtde_entrada, qtde_nos_escondidos)
    peso_cam_oculta_saida = np.random.rand(qtde_nos_escondidos, qtde_saida)
    return peso_ent_camada_oculta, peso_cam_oculta_saida

In [ ]:
peso_cam_oculta_saida


array([[0.56442866],
       [0.81044696],
       [0.46365033],
       [0.10920238]])

In [ ]:
qtd_ent = dic_entrada['qtde_entrada']
qtd_saida = dic_entrada['qtde_saida']
type(qtd_saida)
peso_ent_camada_oculta, peso_cam_oculta_saida = inic_pesos(qtde_nos_escondidos, qtd_ent, qtd_saida)
print (peso_ent_camada_oculta, peso_cam_oculta_saida)

[[0.07281693 0.08046349 0.41915293 0.98674389]
 [0.09238692 0.80152996 0.10748828 0.56428056]] [[0.19843918]
 [0.29857661]
 [0.10951006]
 [0.31813934]]


In [ ]:
peso_cam_oculta_saida

array([[0.19843918],
       [0.29857661],
       [0.10951006],
       [0.31813934]])

In [ ]:
from re import T
def calc_fluxo_volta (X, y, tx_aprend ): #, peso_cam_oculta_saida, peso_ent_camada_oculta):

    # Calculando o erro na camada de saída
    erro_saida = y - saida
#    print ('erro_saida', erro_saida)

    # Atualizando os pesos da camada de saída
    delta_output = erro_saida * calc_derivada_parcial(saida)
#    print ('delta_output', delta_output)
    peso_cam_oculta_saida += np.dot(erro_saida.T, delta_output) * tx_aprend
    #bias_output += np.sum(delta_output, axis=0, keepdims=True) * tx_aprend
    #print ('bias_output: ', bias_output)

    # Calculando o erro na camada oculta
    hidden_error = np.dot(delta_output, peso_cam_oculta_saida.T)

    # Atualizando os pesos da camada oculta
    delta_hidden = hidden_error * calc_derivada_parcial(erro_saida)
    peso_ent_camada_oculta += np.dot(X.T, delta_hidden) * tx_aprend
    #bias_hidden += np.sum(delta_hidden, axis=0, keepdims=True) * tx_aprend

#calc_soma_cam_oculta(entrada, qtde_nos_escondidos, peso_ent_camada_oculta)

In [ ]:
def calc_fluxo_ida(X):
    # Camada oculta
    hidden_output = calc_func_signoide(np.dot(X, peso_ent_camada_oculta))

    # Camada de saída
    output = calc_func_signoide(np.dot(hidden_output, peso_cam_oculta_saida))
    return output

In [ ]:
# Para cada epoca, calcula o

for epoca in range(nr_epocas):
    saida = calc_fluxo_ida(X)
#    print ('saida: ', saida)
    calc_fluxo_volta(X, y, tx_aprend) #, peso_cam_oculta_saida, peso_ent_camada_oculta)
    if epoca % 1000 == 0:
        print(f'Error: {np.mean(np.abs(y - saida)):.4f}')

print("Output after training:")
print(calc_fluxo_ida(X))

UnboundLocalError: local variable 'peso_cam_oculta_saida' referenced before assignment

In [ ]:
import numpy as np

class NeuralNetwork:
    def __init__(self, qtde_entrada, qtde_nos_escondidos, qtde_saida):
        self.qtde_entrada = qtde_entrada
        self.qtde_nos_escondidos = qtde_nos_escondidos
        self.qtde_saida = qtde_saida

        # Inicialização dos pesos
        self.weights_input_hidden = np.random.rand(self.qtde_entrada, self.qtde_nos_escondidos)
        self.weights_hidden_output = np.random.rand(self.qtde_nos_escondidos, self.qtde_saida)

        # Inicialização dos viéses
        #self.bias_hidden = np.random.rand(1, self.qtde_nos_escondidos)
        #self.bias_output = np.random.rand(1, self.qtde_saida)

    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

    def sigmoid_derivative(self, x):
        return x * (1 - x)

    def feedforward(self, X):
        # Camada oculta
        self.hidden_output = self.sigmoid(np.dot(X, self.weights_input_hidden)) # + self.bias_hidden)

        # Camada de saída
        self.output = self.sigmoid(np.dot(self.hidden_output, self.weights_hidden_output)) # + self.bias_output)
        return self.output

    def backward(self, X, y, learning_rate):
        # Calculando o erro na camada de saída
        output_error = y - self.output
        #print ('output_error: ', output_error)

        # Atualizando os pesos da camada de saída
        delta_output = output_error * self.sigmoid_derivative(self.output)
        #print ('delta_output: ', delta_output)
        self.weights_hidden_output += np.dot(self.hidden_output.T, delta_output) * learning_rate
        #self.bias_output += np.sum(delta_output, axis=0, keepdims=True) * learning_rate

        # Calculando o erro na camada oculta
        hidden_error = np.dot(delta_output, self.weights_hidden_output.T)

        # Atualizando os pesos da camada oculta
        delta_hidden = hidden_error * self.sigmoid_derivative(self.hidden_output)
        self.weights_input_hidden += np.dot(X.T, delta_hidden) * learning_rate
        #self.bias_hidden += np.sum(delta_hidden, axis=0, keepdims=True) * learning_rate

# Exemplo de uso
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [1], [1], [0]])

qtde_entrada = 2
qtde_nos_escondidos = 4
qtde_saida = 1

nn = NeuralNetwork(qtde_entrada, qtde_nos_escondidos, qtde_saida)

epochs = 10000
learning_rate = 0.1

for epoch in range(epochs):
    output = nn.feedforward(X)
    nn.backward(X, y, learning_rate)
    if epoch % 1000 == 0:
        print(f'Error: {np.mean(np.abs(y - output)):.4f}')

print("Output after training:")
print(nn.feedforward(X))


Error: 0.4993
Error: 0.4996
Error: 0.4945
Error: 0.4506
Error: 0.3570
Error: 0.2286
Error: 0.1601
Error: 0.1265
Error: 0.1067
Error: 0.0935
Output after training:
[[0.0990723 ]
 [0.91755848]
 [0.91766426]
 [0.07184535]]
