<a href="https://colab.research.google.com/github/AdersonLongo/DevBlockchain/blob/main/Trab1RN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np

dic_entrada = {'qtde_entrada': 3, 'qtde_saida': 1 }
peso_ent_camada_oculta = np.array([])
peso_cam_oculta_saida = np.array([])

# Rede neural para resolver XOR com 2 entradas
#X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
#y = np.array([[0], [1], [1], [0]])

# Rede neural para resolver XOR com 3 entradas
X = np.array([[0, 0, 0], [0, 0, 1], [0, 1, 0], [1, 0, 0], [1, 1, 0], [1, 0, 1], [1, 1, 1]])
y = np.array([[0], [1], [1], [1], [1], [1], [0]])

def calc_func_sigmoide (x):
  return 1 / (1 + np.exp(-x))

def calc_derivada_parcial (x):
  return x * (1-x)

# Inicialização dos pesos\n",
def inic_pesos(qtde_nos_escondidos, qtde_entrada, qtde_saida):
    peso_ent_camada_oculta = np.random.rand(qtde_entrada, qtde_nos_escondidos)
    peso_cam_oculta_saida = np.random.rand(qtde_nos_escondidos, qtde_saida)
    return peso_ent_camada_oculta, peso_cam_oculta_saida

#Solicita os parâmetros de entrada
tx_aprend = float(input(print ("Entre com taxa de aprendizagem: ")))
nr_epocas = int(input(print ("Entre com o número de épocas: ")))
qtde_nos_escondidos = int(input(print ("Entre com a qtde de nós da camada escondida: ")))

# Carrega as variaveis de qtde de entradas e saida para execução
qtd_ent = dic_entrada['qtde_entrada']
qtd_saida = dic_entrada['qtde_saida']
peso_ent_camada_oculta, peso_cam_oculta_saida = inic_pesos(qtde_nos_escondidos, qtd_ent, qtd_saida)

# Para cada epoca
for epoca in range(nr_epocas):

    # Calcula soma da camada de entrada
    #soma_cam_oculta()
# -- Início feedforward
    # Calcula a função sigmoide para a camada oculta
    vetor_ent_sigmoide = np.dot(X, peso_ent_camada_oculta)
    #print ('vetor_ent_sigmoide: ', vetor_ent_sigmoide)
    vetor_saida_sigmoide = calc_func_sigmoide(vetor_ent_sigmoide)
    #print ('vetor_saida_sigmoide: ', vetor_saida_sigmoide)

    # Utiliza a função .dot do numpy para gerar um número para o cálculo da função Sigmoide
    entrada_func_sig = np.dot(vetor_saida_sigmoide, peso_cam_oculta_saida)
    vet_resultado_sigmoide = calc_func_sigmoide(entrada_func_sig)
    #print ("Resultado: ", vet_resultado_sigmoide)


# -- Início backward (X, y, tx_aprend)
    # Calcula o erro entre o resultado esperado e o resultado obtido
    erro = y - vet_resultado_sigmoide
    #print ("erro: ", erro)

    # Imprime o valor do erro ao longo do treinamento a cada 1000
    if epoca % 1000 == 0:
        print(f'Valor do erro: {np.mean(np.abs(y - vet_resultado_sigmoide)):.4f}')

    # Calcula o parametro Delta considerando a camada de saída
    param_delta_saida = erro * calc_derivada_parcial(vet_resultado_sigmoide)
    #print ("param_delta_saida: ", param_delta_saida)

    # Utilizo a função .dot do numpy para gerar um número para o cálculo da função Sigmoide para o cálculo do delta da camada oculta
    peso_cam_oculta_saida += np.dot(vetor_saida_sigmoide.T, param_delta_saida) * tx_aprend
    #print ('erro_cam_oculta:', erro_cam_oculta)

    # Calculando o erro na camada oculta
    erro_cam_oculta = np.dot(param_delta_saida, peso_cam_oculta_saida.T)

    # Calcula o parametro Delta considerando a camada oculta
    param_delta_oculta = erro_cam_oculta * calc_derivada_parcial(vetor_saida_sigmoide) #np.matmul(erro_cam_oculta, calc_derivada_parcial(vetor_saida_sigmoide))    #
    #print ('param_delta_oculta:', param_delta_oculta)

    # Atualizando os pesos da camada oculta
    peso_ent_camada_oculta += np.dot(X.T, param_delta_oculta) * tx_aprend


print("Resultado da rede neural após treinamento de ", nr_epocas, " época(s): ")
print (vet_resultado_sigmoide)
print ("Peso_ent_camada_oculta: ", peso_ent_camada_oculta)
print ("Peso_cam_oculta_saida: ", peso_cam_oculta_saida)


Entre com taxa de aprendizagem: 
None0.1
Entre com o número de épocas: 
None10000
Entre com a qtde de nós da camada escondida: 
None6
Valor do erro: 0.3503
Valor do erro: 0.4005
Valor do erro: 0.3515
Valor do erro: 0.2633
Valor do erro: 0.1637
Valor do erro: 0.1102
Valor do erro: 0.0858
Valor do erro: 0.0720
Valor do erro: 0.0630
Valor do erro: 0.0567
Resultado da rede neural após treinamento de  10000  época(s): 
[[0.08482351]
 [0.95248797]
 [0.95215579]
 [0.98749951]
 [0.94556831]
 [0.94905559]
 [0.06471908]]
Peso_ent_camada_oculta:  [[ 1.37315908 -0.39157748 -0.55296376  3.33588386  0.10160342  1.30770407]
 [-0.94369125 -2.52738441  5.13091676  4.5883527   1.45932228 -0.28369017]
 [-0.71168272  5.86712448 -1.9860124   4.56174789 -0.89919033 -0.55741509]]
Peso_cam_oculta_saida:  [[ 0.85047943]
 [-7.18629899]
 [-5.70298693]
 [12.32400644]
 [-2.82911554]
 [-2.21334561]]
